import React from "react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

import Header from "@/app/components/Header";
import Footer from "@/app/components/Footer";
import GoTop from "@/app/components/GoTop";
import ArticleHome from "../components/ArticleHome";

import product from "@/assets/img/news.jpg";
import blog1 from "@/assets/img/news1.jpg";
import blog2 from "@/assets/img/news2.jpeg";
import blog3 from "@/assets/img/news3.jpg";
import blog4 from "@/assets/img/news4.jpg";

// import TipsHome from "../components/TipsHome";

export default function Blogs() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <GoTop />

      {/* <div className="bg-white">
        <div className="dark:bg-transparent">
          <div className="mx-auto flex flex-col items-center py-12 sm:py-12">
            <div className="w-11/12 sm:w-2/3 lg:flex justify-center items-center flex-col mb-5 ">
              <h1 className="text-4xl md:text-4xl lg:text-4xl text-center text-gray-900 font-bold leading-10">
                Beauty
              </h1>
              <p className="mt-3 md:mt-7 lg:w-10/12 text-gray-900 leading-tight font-normal text-center text-[18px] ">
                Find celebrity beauty secrets, hairstyles, skin care tips, and
                beauty trends. Find new ideas for your hair, makeup, nails and
                more.
              </p>
            </div>
          </div>
        </div>
      </div> */}

      <div className="bg-[#ffc84e] w-full flex items-center py-3">
        <div className="flex flex-col items-center justify-center mx-auto w-11/12 ">
          <h1 className="py-6 text-4xl md:text-4xl lg:text-4xl text-center text-gray-900 font-bold leading-10">
            Latest News
          </h1>
          <div className="flex flex-col w-full">
            <Image src={product} alt="" className="w-full object-cover" />
            <div className="flex flex-col space-y-2 items-center justify-center px-6 md:px-20 py-6 text-center ">
              <span className="text-gray-900 text-2xl md:text-4xl font-bold">
                2024 Ford Mustang Mach-E GT Joins the Bronze Age
              </span>
              <span className="pt-1 font-semibold uppercase text-[11px] text-gray-900">
                by todd lassa
              </span>
            </div>
          </div>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mt-4 mb-4 mx-auto w-full px-3 md:px-0 ">
            <div className="">
              <div className=" bg-transparent group flex  flex-col overflow-hidden ">
                <Link href="/detail" className="relative bg-pink-50">
                  <Image src={blog1} alt="" className="object-cover w-full" />{" "}
                  <div className="absolute opacity-0 group-hover:opacity-75 z-20 inset-0 mix-blend-overlay w-full bg-gradient-to-br from-purple-hot to-teal"></div>
                </Link>{" "}
                <div className="px-0 py-2 pb-4 flex flex-col space-y-1 leading-tight">
                  <h3 className="font-bold text-base md:text-md text-[#333333] leading-tight hover:underline underline-offset-2">
                    <Link href="/detail">
                      Ford Is Slowing F-150 Lightning Production Again
                    </Link>
                  </h3>{" "}
                  <span className="pt-1 font-semibold uppercase text-[11px] text-gray-900">
                    by todd lassa
                  </span>
                </div>
              </div>
            </div>
            <div className="">
              <div className=" bg-transparent group flex flex-col overflow-hidden ">
                <Link href="/detail" className="relative">
                  <Image src={blog2} alt="" className="object-cover w-full" />{" "}
                  <div className="absolute opacity-0 group-hover:opacity-75 z-20 inset-0 mix-blend-overlay w-full bg-gradient-to-br from-purple-hot to-teal"></div>
                </Link>{" "}
                <div className="px-0 py-2 pb-4 flex flex-col space-y-1 leading-tight">
                  <h3 className="font-bold text-base md:text-md text-[#333333] leading-tight hover:underline underline-offset-2">
                    <Link href="/detail">
                      Will Honda Finally Capitalize on EVs in 2024?
                    </Link>
                  </h3>{" "}
                  <span className="pt-1 font-semibold uppercase text-[11px] text-gray-900">
                    by todd lassa
                  </span>
                </div>
              </div>
            </div>
            <div className="">
              <div className=" bg-transparent group flex flex-col overflow-hidden ">
                <Link href="/detail" className="relative">
                  <Image src={blog3} alt="" className="object-cover w-full" />{" "}
                  <div className="absolute opacity-0 group-hover:opacity-75 z-20 inset-0 mix-blend-overlay w-full bg-gradient-to-br from-purple-hot to-teal"></div>
                </Link>{" "}
                <div className="px-0 py-2 pb-4 flex flex-col space-y-1 leading-tight">
                  <h3 className="font-bold text-base md:text-md text-[#333333] leading-tight hover:underline underline-offset-2">
                    <Link href="/detail">
                      2024 Kia EV9 Brings Comfort and 304 Miles of Range
                    </Link>
                  </h3>{" "}
                  <span className="pt-1 font-semibold uppercase text-[11px] text-gray-900">
                    by todd lassa
                  </span>
                </div>
              </div>
            </div>
            <div className="">
              <div className=" bg-transparent group flex flex-col overflow-hidden ">
                <Link href="/detail" className="relative">
                  <Image src={blog4} alt="" className="object-cover w-full" />{" "}
                  <div className="absolute opacity-0 group-hover:opacity-75 z-20 inset-0 mix-blend-overlay w-full bg-gradient-to-br from-purple-hot to-teal"></div>
                </Link>{" "}
                <div className="px-0 py-2 pb-4 flex flex-col space-y-1 leading-tight">
                  <h3 className="font-bold text-base md:text-md text-[#333333] leading-tight hover:underline underline-offset-2">
                    <Link href="/detail">
                      Was 2023 an Awful Year for EV Sales? They Grew 46%
                    </Link>
                  </h3>{" "}
                  <span className="pt-1 font-semibold uppercase text-[11px] text-gray-900">
                    by todd lassa
                  </span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* <TipsHome /> */}
      <ArticleHome />

      <Footer />
    </>
  );
}
