import React from "react";
import Head from "next/head";
import Image from "next/image";

import Header from "@/app/components/Header";
import Footer from "@/app/components/Footer";
import GoTop from "@/app/components/GoTop";


export default function page() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <GoTop />

      <div className="flex bg-[#f2f6f6] min-h-screen pt-10 pb-10 md:pt-[100px]">
        <div className="flex mx-auto w-11/12 md:w-10/12 bg-white rounded-md shadow border">
          <div className="flex py-10 flex-col space-y-10 mx-auto w-10/12">
            <div>
              <span className="text-3xl md:text-4xl font-bold md:leading-snug ">
                Imagine a community of passionate & ambitious learners, all
                working to make a positive impact on the world around them. Now
                imagine your high school :/
              </span>
            </div>
            <div>
              <span className="text-lg  leading-snug text-gray-700">
                We understand that traditional education is important, but it is
                not enough to prepare you for the real world. That&apos;s why we&apos;ve
                created a full-cycle curriculum that goes beyond the boundaries
                of traditional education, providing you with the hands-on
                experience, mentorship, and support you need to turn your dreams
                into realities.
              </span>
            </div>
            <div>
              <span className="text-lg  leading-snug text-gray-700">
                Our team is dedicated to helping you discover your strengths,
                develop your skills, and build a successful future. Whether
                you&apos;re interested in entrepreneurship, technology, arts, or any
                other field, our program will provide you with the resources,
                guidance, and opportunities you need to make the most of your
                potential.
              </span>
            </div>
            <div>
              <span className="text-lg  leading-snug text-gray-700">
                At Ivy Stat, you will join a community of like-minded
                individuals who share your passion and drive. Together, you will
                learn from mentors and experts, collaborate on projects, and
                build networks that will last a lifetime.
              </span>
            </div>
          </div>
        </div>
      </div>

     
      <Footer />
    </>
  );
}
