import React from "react";
import Head from "next/head";
import Link from "next/link";

import Header from "../components/Header";
import Footer from "../components/Footer";

export default function Login() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />


      <div className="flex h-max py-8 md:py-20 bg-white ">
        <div className="flex  w-full2">
          <div className="max-w-full xl:max-w-[1800px] mx-auto flex flex-col justify-center items-center">
            <div className="flex flex-col md:flex-row w-full space-y-3 md:divide-x-2 px-10 md:space-y-0 max-w-full">
              <div className="flex justify-center flex-col md:flex-row">
                <div class="md:pr-[72px] md:max-w-[50%] md:w-[50%] pb-[48px] md:pb-0 ">
                  <div>
                    <div>
                      <h2 class="text-2xl md:text-4xl text-black font-bold">
                        Have a Polaroid account?
                      </h2>
                    </div>
                    <div class="mt-5 lg:mt-6">
                      <p class="text-md lg:text-h5 text-black font-sans leading-5 lg:leading-7">
                        <div>
                          <div>
                            <p class="font-sans">
                              Access it now to save time when you shop.
                            </p>
                          </div>
                        </div>
                      </p>
                    </div>
                    <div class="pt-5 lg:pt-7">
                      <form>
                        <div class="mt-4 lg:mt-5">
                          <div class="pl-4">
                            <label
                              class="text-h6-mobile text-storm font-sans"
                              for="login-email"
                            >
                              Email
                            </label>
                          </div>
                          <div class="mt-2">
                            <input
                              type="text"
                              id="login-email"
                              class="rounded-full border-neutral border-2 w-full h-[48px] px-7 text-body-md text-black font-sans leading-4 placeholder:text-dovegray"
                              placeholder="Email"
                              name="email"
                              value=""
                            />
                          </div>
                        </div>
                        <div class="mt-4 lg:mt-5">
                          <div class="pl-4">
                            <label
                              class="text-h6-mobile text-storm font-sans"
                              for="login-password"
                            >
                              Password
                            </label>
                          </div>
                          <div class="mt-2">
                            <input
                              type="password"
                              id="login-password"
                              class="rounded-full border-neutral border-2 w-full h-[48px] px-7 text-body-md text-black font-sans leading-4 placeholder:text-dovegray"
                              placeholder="Password"
                              name="password"
                              value=""
                            />
                          </div>
                        </div>
                        <div class="pt-6">
                          <button
                            type="submit"
                            class="text-md font-bold rounded-full transition-[all] duration-300 ease-out cursor-pointer bg-black text-white border-2 border-black hover:bg-white hover:text-black hover:border-solid py-3 px-7 w-full"
                          >
                            Sign in
                          </button>
                        </div>
                      </form>
                      <div class="flex justify-center pt-9">
                        <a
                          href="/account/reset-password"
                          class="text-body-md text-black font-bold animated-underline animated-underline-black pb-[2px]"
                        >
                          Forgot your password?
                        </a>
                      </div>
                    </div>
                  </div>
                </div>

                <div class="h-[1px] w-auto md:w-[1px] md:h-auto bg-slate-400/50"></div>

                <div class="md:max-w-[50%] md:w-[50%] md:pl-[72px] pt-[48px] md:pt-0 ">
                  <div>
                    <h2 class="text-2xl md:text-4xl font-bold text-black font-headings">
                      Don’t have an account?
                    </h2>
                  </div>
                  <div class="mt-5 md:mt-6">
                    <p class="text-md md:text-lg text-black font-semibold leading-5 md:leading-6">
                      <div>
                        <div>
                          <p class="font-sans">
                            Create your own Polaroid account today. It makes
                            shopping smoother and faster, while also earning you
                            reward points on every purchase.
                          </p>
                          <p class="font-sans"></p>
                        </div>
                      </div>
                    </p>
                  </div>
                  <div class="mt-9">
                    <a
                      href="/account/register"
                      class="inline-flex items-center justify-center bg-black text-md text-white border-2 border-black border-solid font-bold rounded-full text-center h-[48px] px-7 w-full md:w-auto hover:bg-white hover:text-black transition-[all] duration-300 ease-out"
                    >
                      Create your account
                    </a>
                  </div>
                </div>
              </div>

            </div>
          </div>
        </div>
      </div>

      <Footer />
    </>
  );
}
