import Image from 'next/image'
import Head from "next/head";

import Header from './components/Header'
import Footer from './components/Footer'
// import AdsModal from './components/AdsModal'
import GoTop from './components/GoTop';
import SubscribeForm from './components/SubscribeForm';
import NewsFeed from './components/NewsFeed';
import CookieConsent from './components/CookieConsent';
import Hero from './components/Hero';
import ArticleHome from './components/ArticleHome';

export default function Home() {
  return (
    <>
     <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

    <Header />
    <GoTop />
    <CookieConsent />
    <NewsFeed />
    <Hero />
    <ArticleHome />
    <SubscribeForm />
    <Footer />
    </>
  )
}
