import React from "react";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";

import Header from "../components/Header";
import Footer from "../components/Footer";
import GoTop from "../components/GoTop";
import FormulaNav from "../components/FormulaNav";
import ScheduleRace from "../components/ScheduleRace";

import news1 from "@/assets/gallery/news1.jpg";
import news2 from "@/assets/gallery/news2.jpg";
import news3 from "@/assets/gallery/news3.jpg";
import article1 from "@/assets/gallery/article1.jpg";
import article2 from "@/assets/gallery/article2.jpg";
import article3 from "@/assets/gallery/article3.jpg";
import article4 from "@/assets/gallery/article4.jpg";
import article5 from "@/assets/gallery/article5.jpg";
import article6 from "@/assets/gallery/article6.jpg";
import article7 from "@/assets/gallery/article7.jpg";
import article8 from "@/assets/gallery/article8.jpg";

import f1 from "@/assets/icons/f1.png";

export default function F1() {
  const newsData = [
    {
      title: "Charles Leclerc to remain at Ferrari beyond 2024",
      img: article1,
    },
    {
      title: "AlphaTauri renamed Visa Cash App RB for 2024",
      img: article2,
    },
    {
      title: "F1 adds Madrid street race to calendar from 2026",
      img: article3,
    },
    {
      title: "Allison to remain at Mercedes on long-term deal",
      img: article4,
    },
    {
      title: "New Haas boss 'not trying to be Guenther Steiner'",
      img: article5,
    },
    {
      title: "Norris extension a priority for McLaren",
      img: article8,
    },
    {
      title: "McLaren reveals car livery for 2024 F1 season",
      img: article7,
    },
    {
      title: "McLaren CEO: Red Bull-AlphaTauri ties an 'issue'",
      img: article1,
    },
  ];

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ScheduleRace />
      <Header />
      <GoTop />
      <FormulaNav />

      <div
        data-section="hero-sectionIndex=0"
        className="relative w-full flex flex-col justify-center md:h-[480px] mx-auto h-[193px] xs:items-center xs:justify-center md:items-start md:justify-center text-white"
      >
        <div className="absolute w-full h-full">
          <div className="w-full h-full">
            <div className="hidden md:block md:w-full md:h-full relative animate-[fadeIn_0.3s_ease-out]">
              <Image src={news2} alt="" className="object-cover w-full" />
            </div>
          </div>
        </div>
        <div className="z-10 h-full flex flex-col justify-center bg-gray-900/60 items-center text-center  xs:my-[12px] md:my-[48px] px-[12px] md:px-[30px] md:w-[380px] relative xs:items-center xs:text-center xs:justify-center md:items-start md:text-left md:justify-center">
          <h3 className="font-bold mb-[12px] text-2xl md:text-3xl md:mb-[20px]">
          Verstappen wins final race of 2023 as Mercedes hold off Ferrari for second in standings
          </h3>
          {/* <div className="font-bold text-6xl md:text-h1 mb-[8px] md:mb-[24px]">
            <div>
              <div>
                <h1></h1>
              </div>
            </div>
          </div> */}
          <div className="flex gap-3"></div>
        </div>
      </div>

      <main className="bg-white pt-9">
        <div className="py-3 mx-auto w-11/12 ">
          <div className="flex w-full flex-col space-y-2">
            <div className="flex flex-row space-x-2 items-center ">
              <Image src={f1} alt="" className="object-cover w-12" />
              <div>
                <span className="text-lg font-semibold md:font-bold tracking-tighter capitalize text-gray-800">
                  Top Headlines
                </span>
              </div>
            </div>
            <div className="grid grid-cols-2 gap-2">
              {newsData.map((data, index) => {
                return (
                  <div className='flex before:inline items-center before:px-1.5 before:text-sm before:content-[">"] ' key={index}>
                    <Link href={"/"} className="text-gray-900 hover:text-blue-600">
                    <span className="text-xs ">{data.title}</span>
                    </Link>
                  </div>
                );
              })}
            </div>
          </div>
        </div>
      </main>

      <div className="h-max mx-auto w-full lg:w-1/2 flex flex-col space-y-4 md:px-4 py-5 md:py-4 lg:px-0 justify-center2 items-center2 bg-white">
        <div className="flex flex-row flex-wrap  mx-auto w-full md:w-12/12 ">
          {newsData.map((data, index) => {
            return (
              <div className="px-3 py-3 w-1/2 md:w-1/3 lg:w-1/3" key={index}>
                <div className=" bg-white group flex flex-col overflow-hidden hover:scale-110 shadow-md ">
                  <Link href="" className="relative">
                    <Image src={data.img} alt="" className="w-80" />{" "}
                    <div className="absolute opacity-0 group-hover:opacity-75 z-20 inset-0 mix-blend-overlay w-full bg-gradient-to-br from-purple-hot to-teal"></div>
                  </Link>{" "}
                  <div className="px-3 py-2 pb-2 flex flex-col space-y-1 leading-tight">
                    <div className="font-semibold text-[11px]  uppercase text-red-500">
                      News
                    </div>
                    <div className="font-semibold pb-2 text-[#002f6c]">
                      <Link href="/">
                        <span className="text-md leading-3 ">{data.title}</span>
                      </Link>
                    </div>{" "}
                    <div className="flex flex-between">
                      <div>
                        <span className="text-[10px] text-gray-500 capitalize">
                          mon 29 jan, 2024
                        </span>
                      </div>
                      <span></span>
                    </div>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      </div>

      <Footer />
    </>
  );
}
