import React from 'react'
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";

import Header from "../components/Header";
import Footer from "../components/Footer";
import GoTop from "../components/GoTop";

import review from "@/assets/reviews/review.jpg"
import review1 from "@/assets/reviews/review1.jpg"
import review2 from "@/assets/reviews/review2.jpg"
import review3 from "@/assets/reviews/review3.jpg"
import review4 from "@/assets/reviews/review4.jpg"
import review5 from "@/assets/reviews/review5.jpg"
import review6 from "@/assets/reviews/review6.jpg"
import review7 from "@/assets/reviews/review7.jpg"
import review8 from "@/assets/reviews/review8.jpg"
import review9 from "@/assets/reviews/review9.jpg"
import review10 from "@/assets/reviews/review10.jpg"
import review11 from "@/assets/reviews/review11.jpg"
import review12 from "@/assets/reviews/review12.jpg"
import review13 from "@/assets/reviews/review13.jpg"
import review14 from "@/assets/reviews/review14.jpg"
import review15 from "@/assets/reviews/review15.jpg"

export default function Review() {
    const reviewData = [
       
        {
            title: "2024 Volkswagen Jetta Review: Classic Competence",
            img: review1
        },
        {
            title: "2024 Genesis GV60 Review: Generous Genesis",
            img: review2
        },
        {
            title: "Driven: 2023 Toyota GR Corolla Is The Ultimate Fizz Machine",
            img: review3
        },
        {
            title: "Driven: 2023 Dodge Challenger Swinger Edition Is The Most V8 Fun You Can Have With Your Clothes On",
            img: review4
        },
        {
            title: "2024 Porsche Macan Electric First Look Review: Electric Sequel",
            img: review5
        },
        {
            title: "2023 Ford Transit Trail Camper Van Review: Bring On The Van Life",
            img: review6
        },
        {
            title: "2024 Audi A8 Review: Luxury And Performance Without Ostentation",
            img: review7
        },
        {
            title: "2025 Cadillac CT5-V Blackwing First Look Review: Modernizing A Future Classic",
            img: review8
        },
        {
            title: "2025 Cadillac CT5-V First Look Review: The Best Of Both Worlds",
            img: review9
        },
        {
            title: "2023 Fisker Ocean Review: Mile And Wave, Boys",
            img: review10
        },
        {
            title: "2024 Kia EV9 First Drive Review: Deserving Of Its Flagship Status",
            img: review11
        },
        {
            title: "2025 Volkswagen Golf GTI First Look Review: The Automatic Choice",
            img: review12
        },
        {
            title: "2025 Chevrolet Equinox First Look Review: More Of Everything You Need",
            img: review13
        },
        {
            title: "2023 Bentley Flying Spur Speed Review: Gentleman Speedster",
            img: review14
        },
        {
            title: "McLaren 750S Review: Civilized Speedster",
            img: review15
        },
    ]

  return (
    <>
        <Head>
        <title>Create Next App</title>
        <meta title="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <GoTop />

      <div className="bg-white w-full flex items-center py-3">
        <div className="flex flex-col items-center justify-center mx-auto w-11/12 ">
          <h1 className="py-6 text-4xl md:text-4xl lg:text-4xl text-center text-gray-900 font-bold leading-10">
            Reviews
          </h1>
          <div className="flex flex-col w-full">
            <Image src={review} alt="" className="w-full object-cover" />
            <div className="flex flex-col space-y-2 items-center justify-center px-6 md:px-20 py-6 text-center ">
              <Link href={"/"} className='hover:underline underline-offset-2'>
              <span className="text-gray-900 text-2xl md:text-4xl font-bold">
              Driven: 2024 Toyota Crown Is A Cool Sedan, But It Doesn&apos;t Make Sense
              </span>
              </Link>
              {/* <span className="pt-1 font-semibold uppercase text-[11px] text-gray-900">
                by todd lassa
              </span> */}
            </div>
          </div>
          
        </div>
      </div>

      <div className="flex bg-white min-h-screen pt-1 pb-10 md:pt-[1px]">
        <div className="flex flex-row w-full">
          <div className="flex flex-1 flex-col items-center2 justify-center2 relative">
            <div className="flex flex-1 flex-col mx-auto pb-18 max-w-md md:max-w-4xl ">
              <section className="w-full mx-auto  mt-10 md:mt-10 px-5 ">
                {/* <div>
                  <div className="py-6">
                    <Image src={blog} alt="" className="w-full" />
                  </div>

                  <Link
                    href={"/blogs/3"}
                    className="flex text-3xl font-bold tracking-tighter md:text-5xl lg:text-7xl text-black hover:underline underline-offset-2"
                  >
                    <span className="text-center">
                      I Tried PRF Fillers for My 30th Birthday—Here’s What I
                      Wish I’d Known First
                    </span>
                  </Link>
                  <p className="max-w-3xl mt-6 text-lg font-medium md:text-xl lg:text-2xl text-black leading-snug">
                    People ask all the time – is the ZZ plant poisonous? Here’s
                    the details! ZZ plants known by the botanical name of
                    Zamioculcas Zamiifolia have become a very popular houseplant
                    over..
                  </p>
                  <div className="flex flex-col py-4 items-center justify-center space-y-1">
                    <p className="text-sm font-semibold text-[#757575]">
                      By Brigitt Earley
                    </p>
                    <span className="text-xs text-gray-900">
                      January 6, 2024
                    </span>
                  </div>
                  <div className="h-px bg-mercury"></div>
                </div> */}
                <div>
                  {/* tweet */}
                  {/* <div className="flex min-w-0 flex-1 flex-col py-2">
                    <div className="w-full rounded p-4 bg-[##14ada8]">
                      <div className="flex flex-col space-y-1 md:space-y-2">
                        <Link
                          href={"/blogs/3"}
                          className="my-[0.25em] mx-[0em] overflow-hidden break-words text-md md:text-lg leading-tight md:leading-tight font-semibold text-gray-900 hover:text-indigo-600"
                        >
                          Apple&apos;s iPhone 15 Event Recap: New Phones, New
                          Watches, and USB-C
                        </Link>
                        <span className="text-sm md:text-lg leading-tight md:leading-tight break-words text-justify">
                          Apple&apos;s annual fall product-launch event brought
                          few surprises but still delivered big blog: The
                          company unveiled four iPhone 15 models
                        </span>
                      </div>
                      <div className="pt-2 ">
                        <Tweet
                          id="1724501306109579518"
                          className="w-1/2 md:w-full"
                        />
                      </div>
                    </div>
                    <div className="h-px bg-mercury"></div>
                  </div> */}
                  <div className="flex w-full space-x-4">
                    <div>
                      {reviewData.map((data, index) => {
                        return (
                          <div
                            className="text-tundora no-underline"
                            key={index}
                          >
                            <div className="my-[1em] mx-[0em] flex md:items-center w-full bg-transparent leading-[1.25em]">
                              <div className="m-0 mr-2 md:mr-5 flex aspect-[16/9] md:aspect-[16/8] h-fit flex-19 items-center justify-center">
                                <Link href={"/blogs/blog-one"}>
                                  <Image
                                    alt=""
                                    src={data.img}
                                    className="h-full2 w-full2 object-cover"
                                    style={{ color: "transparent" }}
                                  />
                                </Link>
                              </div>
                              <div className=" flex w-2/3 md:max-w-[55%]  flex-1 flex-col space-y-1 md:space-y-2">
                                <div className="flex items-center flex-wrap py-0.5 ">
                                  <div className="text-[14px] font-bold text-[#5492e0] uppercase">
                                    test drive
                                  </div>
                                </div>
                                <Link
                                  href={"/blogs/blog-one"}
                                  className="text-gray-900 hover:underline underline-offset-2"
                                >
                                  <span className="my-[0.25em] mx-[0em] overflow-hidden break-words text-md md:text-2xl leading-tight md:leading-tight font-bold">
                                    {data.title}
                                  </span>
                                </Link>
                                <span className="hidden md:block text-md text-gray-900 md:text-md leading-tight md:leading-tight tracking-tight break-words text-justify">
                                  The next generation of the A6 transitions to
                                  an all-electric powertrain, providing a range
                                  of up to 435 miles and rapid 270 kW charging
                                  capability
                                </span>
                                <div className="flex flex-row space-x-3">
                                  <p className="text-sm font-semibold text-[#757575]">
                                    By Brigitt Earley
                                  </p>
                                  <div className="flex space-x-1 items-center">
                                    <svg
                                      xmlns="http://www.w3.org/2000/svg"
                                      viewBox="0 0 24 24"
                                      fill="currentColor"
                                      className="w-4 h-4"
                                    >
                                      <path
                                        fillRule="evenodd"
                                        d="M4.848 2.771A49.144 49.144 0 0 1 12 2.25c2.43 0 4.817.178 7.152.52 1.978.292 3.348 2.024 3.348 3.97v6.02c0 1.946-1.37 3.678-3.348 3.97-1.94.284-3.916.455-5.922.505a.39.39 0 0 0-.266.112L8.78 21.53A.75.75 0 0 1 7.5 21v-3.955a48.842 48.842 0 0 1-2.652-.316c-1.978-.29-3.348-2.024-3.348-3.97V6.741c0-1.946 1.37-3.68 3.348-3.97Z"
                                        clipRule="evenodd"
                                      />
                                    </svg>
                                    <span className="text-[11px] text-gray-900">
                                      28
                                    </span>
                                  </div>

                                  {/* <span className="text-xs text-gray-900">
                                    January 6, 2024
                                  </span> */}
                                </div>
                              </div>
                            </div>
                            <div className="h-px bg-mercury"></div>
                          </div>
                        );
                      })}
                    </div>
                  </div>
                </div>
                {/* load more */}
                <div className="mt-5 w-full rounded py-3 text-[#333333] hover:text-white text-center bg-[#ffc84e] hover:bg-gray-500 cursor-pointer">
                  <span className="font-bold ">Read more</span>
                </div>
              </section>
            </div>
          </div>
        </div>
      </div>


      <Footer />
    </>
  )
}
