import React from 'react'
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";

import Header from "../../components/Header";
import Footer from "../../components/Footer";
import GoTop from "../../components/GoTop";
import FormulaNav from '../../components/FormulaNav';
import ScheduleRace from '../../components/ScheduleRace';

import mercedes from "@/assets/icons/mercedes.png"
import alpine from "@/assets/icons/alpine.png"
import haas from "@/assets/icons/haas.png"
import redbull from "@/assets/icons/redbul.png"
import mclaren from "@/assets/icons/mclaren.png"
import aston from "@/assets/icons/aston.png"
import ferrari from "@/assets/icons/ferari.png"
import alpha from "@/assets/icons/alpha.png"
import william from "@/assets/icons/wiliam.png"
import sauber from "@/assets/icons/sauber.png"

import car_mercedes from "@/assets/cars/mercedes.png"
import car_alpine from "@/assets/cars/alpine.png"
import car_haas from "@/assets/cars/haas.png"
import car_redbull from "@/assets/cars/redbul.png"
import car_mclaren from "@/assets/cars/mclaren.png"
import car_aston from "@/assets/cars/aston.png"
import car_ferrari from "@/assets/cars/ferrari.png"
import car_alpha from "@/assets/cars/sauber.png"
import car_william from "@/assets/cars/wiliam.png"
import car_sauber from "@/assets/cars/sauber.png"


export default function Teams() {

  const teams = [
   
    {
      name: "Alpine",
      logo: alpine,
      car: car_alpine
    },
    {
      name: "Aston Martin",
      logo: aston,
      car: car_aston
    },
    {
      name: "Ferrari",
      logo: ferrari,
      car: car_ferrari
    },
    {
      name: "Haas",
      logo: haas,
      car: car_haas
    },
    {
      name: "McLaren",
      logo: mclaren,
      car: car_mclaren
    },
    {
      name: "Mercedes",
      logo: mercedes,
      car: car_mercedes
    },
    {
      name: "Red Bull",
      logo: redbull,
      car: car_redbull
    },
    {
      name: "Williams",
      logo: william,
      car: car_william
    },
    {
      name: "Kick Sauber",
      logo: sauber,
      car: car_sauber
    },
    {
      name: "AlphaTauri",
      logo: alpha,
      car: car_sauber
    },
  ]

  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ScheduleRace />
      <Header />
      <GoTop />
      <FormulaNav />

      <main className="bg-white min-h-screen">
        <div className="py-3 mx-auto w-11/12 ">
          <div className="flex w-full flex-col space-y-2">
            <div className="flex flex-col md:flex-row justify-between pt-5">
              <div>
                <span className="text-2xl font-semibold md:font-bold tracking-tighter capitalize text-gray-800">
                  F1 Teams - 2024
                </span>
              </div>
              <div className="flex items-center justify-between px-2 border border-gray-300 bg-white rounded-full w-20 h-8">
                <span className="text-[11px] text-gray-900 font-semibold">
                  2024
                </span>
                <span>
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 24 24"
                    strokeWidth={1.5}
                    stroke="currentColor"
                    className="w-3 h-3"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      d="m19.5 8.25-7.5 7.5-7.5-7.5"
                    />
                  </svg>
                </span>
              </div>
            </div>
            <div className="w-full overflow-x-auto py-4 ">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {teams.map((data, index) => {
                  return (
                    <div className="px-3 py-3" key={index}>
                      <div className="group flex flex-col overflow-hidden hover:scale-105 shadow-lg border px-0">
                        <Link href={"/"} className="relative">
                          <div className="flex pt-2 justify-between items-center leading-tight py-1 border-b-4 border-red-300">
                            <div className='bg-gray-900 text-white px-4 rounded-r-md'>
                              <span className="capitalize text-2xl font-bold">
                                {data.name}
                              </span>
                            </div>
                            <div className='flex px-2'>
                            <div className='w-8'>
                              <Image src={data.logo} alt='' className='' />
                            </div>
                            </div>
                          </div>

                          <div className="flex w-full justify-center pt-2">
                            
                            <Image src={data.car} alt="" className=" h-full" />{" "}
                          </div>
                        </Link>{" "}
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>
          </div>
        </div>
      </main>

      <Footer />
    </>
  )
}
