import React from "react";
import Head from "next/head";
import Link from "next/link";

import Header from "../components/Header";
import Footer from "../components/Footer";

export default function Register() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <div className="flex h-max py-8 md:py-20 bg-white ">
        <div className="flex  w-full2">
          <div className="max-w-full xl:max-w-[1800px] mx-auto flex flex-col justify-center items-center">
            <div className="flex flex-col md:flex-row w-full space-y-3 md:divide-x-2 px-10 md:space-y-0 max-w-full">
              <div className="flex justify-center flex-col md:flex-row">
                <div className="md:pr-[72px] md:max-w-[50%] md:w-[50%] pb-[48px] md:pb-0 ">
                  <div>
                    <div>
                      <h2 className="text-2xl md:text-4xl text-black font-bold">
                        Create your account
                      </h2>
                    </div>
                    <div className="mt-5 lg:mt-6">
                      <p className="text-md lg:text-h5 text-black font-sans leading-5 lg:leading-7">
                        <div>
                          <div>
                            <p className="font-sans">
                              Create your own Polaroid account today. It makes
                              shopping smoother and faster, while also earning
                              you reward points on every purchase.
                            </p>
                          </div>
                        </div>
                      </p>
                    </div>
                    <div className="pt-5 lg:pt-4">
                      <form>
                        <div className="mt-4 lg:mt-5">
                          <div className="pl-4">
                            <label
                              className="text-h6-mobile text-storm font-sans text-black"
                              for="register-first-name"
                            >
                              First name
                            </label>
                          </div>
                          <div className="mt-2">
                            <input
                              id="register-first-name"
                              className="rounded-full border-neutral border-2 w-full h-[48px] px-7 text-body-md text-black font-sans leading-4 placeholder:text-dovegray"
                              placeholder="First name"
                              type="text"
                              name="firstName"
                              value=""
                            />
                          </div>
                        </div>
                        <div className="mt-4 lg:mt-5">
                          <div className="pl-4">
                            <label
                              className="text-h6-mobile text-storm font-sans text-black"
                              for="register-last-name"
                            >
                              Last name
                            </label>
                          </div>
                          <div className="mt-2">
                            <input
                              id="register-last-name"
                              className="rounded-full border-neutral border-2 w-full h-[48px] px-7 text-body-md text-black font-sans leading-4 placeholder:text-dovegray"
                              placeholder="Last name"
                              type="text"
                              name="lastName"
                              value=""
                            />
                          </div>
                        </div>
                        <div className="mt-4 lg:mt-5">
                          <div className="pl-4">
                            <label
                              className="text-h6-mobile text-storm font-sans text-black"
                              for="login-email"
                            >
                              Email
                            </label>
                          </div>
                          <div className="mt-2">
                            <input
                              type="text"
                              id="login-email"
                              className="rounded-full border-neutral border-2 w-full h-[48px] px-7 text-body-md text-black font-sans leading-4 placeholder:text-dovegray"
                              placeholder="Email"
                              name="email"
                              value=""
                            />
                          </div>
                        </div>
                        <div className="mt-4 lg:mt-5">
                          <div className="pl-4">
                            <label
                              className="text-h6-mobile text-storm font-sans text-black"
                              for="login-password"
                            >
                              Password
                            </label>
                          </div>
                          <div className="mt-2">
                            <input
                              type="password"
                              id="login-password"
                              className="rounded-full border-neutral border-2 w-full h-[48px] px-7 text-body-md text-black font-sans leading-4 placeholder:text-dovegray"
                              placeholder="Password"
                              name="password"
                              value=""
                            />
                          </div>
                        </div>
                        <div className="flex items-center pt-7 lg:pt-5">
                          <button
                            type="button"
                            role="checkbox"
                            aria-checked="false"
                            data-state="unchecked"
                            value="on"
                            className="h-6 w-6 border-2 border-black rounded shrink-0"
                          ></button>
                          <input
                            type="checkbox"
                            aria-hidden="true"
                            name="termsConditions"
                            tabindex="-1"
                            value="on"
                            style={{ transform: 'translateX(-100%)', position: 'absolute', pointerEvents: 'none', opacity: 0, margin: '0px', width: '24px', height: '24px'}}
                          />
                          <p className="text-md-mobile text-black font-sans ml-[11px] cursor-pointer leading-tight">
                            <div>
                              <div>
                                <p className="font-sans">
                                  I have read and agree to the{" "}
                                  <Link href="/privacy" className="underline">
                                    <span>
                                      Privacy Policy
                                    </span>
                                  </Link>{" "}
                                  and{" "}
                                  <span>
                                    <Link
                                      href="/terms"
                                      className="underline"
                                    >
                                      Loyalty Terms &amp; Conditions
                                    </Link>
                                    .
                                  </span>
                                </p>
                              </div>
                            </div>
                          </p>
                        </div>
                        <div className="pt-6">
                          <button
                            type="submit"
                            className="text-md font-bold rounded-full transition-[all] duration-300 ease-out cursor-pointer bg-black text-white border-2 border-black hover:bg-white hover:text-black hover:border-solid py-3 px-7 w-full"
                          >
                            Create Account
                          </button>
                        </div>
                      </form>
                      <div className="flex justify-center pt-9">
                        <Link
                          href="/login"
                          className="text-body-md text-black font-bold animated-underline animated-underline-black pb-[2px]"
                        >
                          Return to login
                        </Link>
                      </div>
                    </div>
                  </div>
                </div>

                <div className="h-[1px] w-auto md:w-[1px] md:h-auto bg-slate-400/50"></div>

                <div className="md:max-w-[50%] md:w-[50%] md:pl-[72px] pt-[48px] md:pt-0 ">
                  <div>
                    <h2 className="text-2xl md:text-4xl font-bold text-black font-headings">
                    Already have an account?
                    </h2>
                  </div>
                  <div className="mt-5 md:mt-6">
                    <p className="text-md md:text-lg text-black font-semibold leading-5 md:leading-6">
                      <div>
                        <div>
                          <p className="font-sans">
                          Access it now to save time when you shop.
                          </p>
                          <p className="font-sans"></p>
                        </div>
                      </div>
                    </p>
                  </div>
                  <div className="mt-9">
                    <Link
                      href="/login"
                      className="flex items-center justify-center bg-white text-black border-2 border-black border-solid  text-md font-bold rounded-full text-center h-[48px] px-7 w-full md:w-auto transition-[all] duration-300 ease-out hover:bg-black hover:text-white"
                    >
                      Login
                    </Link>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <Footer />
    </>
  );
}
